apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: redb5wxey-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: redb5wxey-nodejs 
  name: redb5wxey-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: redb5wxey-nodejs 
